# Generated by Django 3.0.3 on 2020-03-10 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=256, verbose_name='aluno')),
                ('student_email', models.CharField(max_length=256, verbose_name='email')),
                ('grade_1', models.IntegerField(default=0, verbose_name='competência 1')),
                ('grade_2', models.IntegerField(default=0, verbose_name='competência 2')),
                ('grade_3', models.IntegerField(default=0, verbose_name='competência 3')),
                ('grade_4', models.IntegerField(default=0, verbose_name='competência 4')),
                ('grade_5', models.IntegerField(default=0, verbose_name='competência 5')),
                ('final_grade', models.IntegerField(default=0, editable=False, verbose_name='nota final')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='última modificação')),
                ('essay_unredacted', models.FileField(upload_to='', verbose_name='redação')),
                ('essay_redacted', models.FileField(upload_to='', verbose_name='redação corrigida')),
                ('has_essay', models.BooleanField(editable=False)),
                ('has_correction', models.BooleanField(editable=False)),
            ],
            options={
                'verbose_name': 'redação',
                'verbose_name_plural': 'redações',
            },
        ),
        migrations.CreateModel(
            name='NotificationMode',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTiming',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='EssayConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_mode', models.ManyToManyField(to='essay.NotificationMode')),
                ('notification_timing', models.ManyToManyField(to='essay.NotificationTiming')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuração',
                'verbose_name_plural': 'configurações',
            },
        ),
    ]
