# Generated by Django 3.0.3 on 2020-03-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay',
            options={'ordering': ('last_modified', 'has_essay', 'has_correction'), 'verbose_name': 'redação', 'verbose_name_plural': 'redações'},
        ),
    ]
