# Generated by Django 3.0.3 on 2020-03-10 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essay', '0002_auto_20200310_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EssayConfiguration',
            new_name='NotificationConfiguration',
        ),
        migrations.AlterModelOptions(
            name='notificationmode',
            options={'verbose_name': 'LOOKUP_MODE', 'verbose_name_plural': 'LOOKUP_MODES'},
        ),
        migrations.AlterModelOptions(
            name='notificationtiming',
            options={'verbose_name': 'LOOKUP_TIMING', 'verbose_name_plural': 'LOOKUP_TIMINGS'},
        ),
        migrations.AlterField(
            model_name='notificationmode',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationtiming',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
