# Generated by Django 3.0.3 on 2020-03-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_auto_20200312_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de entrega'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='last_modified',
            field=models.DateField(blank=True, null=True, verbose_name='última modificação'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='upload_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de submissão'),
        ),
    ]
