# Generated by Django 3.0.3 on 2020-03-13 02:36

from django.db import migrations, models
import essay.models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0003_auto_20200312_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='enviado'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=essay.models.essays_upload_to, verbose_name='redação'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='final_grade',
            field=models.IntegerField(default=0, verbose_name='nota final'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='has_correction',
            field=models.BooleanField(default=False, editable=False, verbose_name='correção finalizada'),
        ),
        migrations.AlterField(
            model_name='notificationconfiguration',
            name='event',
            field=models.CharField(choices=[('ON_ESSAY_UPLOAD', 'Upload de Redação'), ('ON_SINGLE_CORRECTION_DONE', 'Correção Completa'), ('ON_ALL_CORRECTIONS_DONE', 'Todas as Correções Completas'), ('ON_DELIVERY_DATE_ARRIVED', 'Data Final de Entrega Atingida')], max_length=32, verbose_name='evento'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=essay.models.redactions_upload_to, verbose_name='correção'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='grade_1',
            field=models.IntegerField(default=0, verbose_name='competência 1'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='grade_2',
            field=models.IntegerField(default=0, verbose_name='competência 2'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='grade_3',
            field=models.IntegerField(default=0, verbose_name='competência 3'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='grade_4',
            field=models.IntegerField(default=0, verbose_name='competência 4'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='grade_5',
            field=models.IntegerField(default=0, verbose_name='competência 5'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='grades_average',
            field=models.IntegerField(default=0, editable=False, verbose_name='nota'),
        ),
    ]
