# Generated by Django 3.0.3 on 2020-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0004_auto_20200310_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='has_correction',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='has_essay',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
