# Generated by Django 3.0.3 on 2020-03-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0004_auto_20200312_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='send_mode_quantity',
        ),
    ]
