# Generated by Django 3.0.3 on 2020-03-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0005_remove_school_send_mode_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average_grade',
            field=models.IntegerField(default=0, verbose_name='nota média'),
        ),
        migrations.AddField(
            model_name='student',
            name='number_of_essays',
            field=models.IntegerField(default=0, verbose_name='número de redações'),
        ),
    ]
