# Generated by Django 3.0.3 on 2020-03-10 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0005_auto_20200310_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essay',
            name='has_correction',
            field=models.BooleanField(default=False, editable=False, verbose_name='corrigida'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='last_modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
