# Generated by Django 3.0.3 on 2020-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0007_auto_20200310_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='essay_redacted',
            field=models.FileField(blank=True, null=True, upload_to='essay/uploads', verbose_name='redação corrigida'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='essay_unredacted',
            field=models.FileField(blank=True, null=True, upload_to='essay/uploads', verbose_name='redação'),
        ),
    ]
