# Generated by Django 3.0.3 on 2020-03-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0008_auto_20200310_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='notified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='last_modified',
            field=models.DateTimeField(editable=False, verbose_name='última modificação'),
        ),
    ]
