# Generated by Django 3.0.3 on 2020-03-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0008_auto_20200313_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='triage_done',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='notificationconfiguration',
            name='event',
            field=models.CharField(choices=[('ON_ESSAY_UPLOAD', 'Upload de Redação'), ('ON_MONITOR_ASSIGNMENT', 'Determinação de Monitor'), ('ON_SINGLE_CORRECTION_DONE', 'Correção Completa'), ('ON_ALL_CORRECTIONS_DONE', 'Todas as Correções Completas'), ('ON_DELIVERY_DATE_ARRIVED', 'Data Final de Entrega Atingida')], max_length=32, verbose_name='evento'),
        ),
        migrations.AlterField(
            model_name='notificationconfiguration',
            name='mode',
            field=models.CharField(choices=[('MODE_MAIL', 'Email')], max_length=32, verbose_name='plataforma'),
        ),
    ]
