# Generated by Django 3.0.3 on 2020-03-11 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essay', '0009_auto_20200310_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='has_monitor',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='essay',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='monitor'),
        ),
    ]
