# Generated by Django 3.0.3 on 2020-03-13 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0009_auto_20200313_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='last_redaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_redaction', to='essay.Redaction'),
        ),
    ]
