# Generated by Django 3.0.3 on 2020-03-18 18:03

from django.db import migrations, models
import django.db.models.deletion
import essay.models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0010_essay_last_redaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essay',
            options={'ordering': ('upload_date', 'last_modified', 'has_essay', '-has_correction'), 'verbose_name': 'redação', 'verbose_name_plural': 'redações'},
        ),
        migrations.AlterField(
            model_name='essay',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última modificação'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='last_redaction',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_redaction', to='essay.Redaction'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essay.Student', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='file',
            field=models.FileField(upload_to=essay.models.redactions_upload_to, verbose_name='correção'),
        ),
    ]
