# Generated by Django 3.0.3 on 2020-03-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0010_auto_20200310_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='student_email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='email'),
        ),
    ]
