import os, django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "services.settings")
django.setup()
from essay.models import School, Student
juazeiro_ppa_students = [
    'BÁRBARA KARINE SÁ ALVES',
    'BARBARA MARIA ARAUJO DE LUCENA',
    'BEATRIZ CÂNDIDO MONTEIRO DA SILVA',
    'BEATRYZ COÊLHO LOSS',
    'DANIEL PEREIRA BRIGIDO RODRIGUES',
    'DEYSIANE PARENTE DO NASCIMENTO',
    'EDNA PATRÍCIA ANGELO LEITE',
    'EDUARDA FEITOSA BEZERRA',
    'FRANCISCO DE ASSIS GUEDES  DE O. FILHO',
    'GABRIEL CARLOS CARVALHO PINHEIRO',
    'GARDENIA SAMPAIO MOREIRA',
    'GUILHERME MARTINS B. EMERICIANO',
    'HÉRLON HEMERSON SILVA BRITO',
    'HERMES LEANDRO DA SILVA NETO',
    'ISABEL FELIPE VÁSQUEZ',
    'ISADORA DE FARIAS SIQUEIRA',
    'ITALO SANTANA VIEIRA',
    'JORDANIA SILVA MAGALHÃES FERRAZ',
    'JOSÉ ALFREDO SILVA NETO',
    'KAREN BRANDÃO MACIEL CORDEIRO',
    'LARA ALMINO DE SOUZA NOBRE',
    'LARISSA AZEVÊDO FREIRE LEITE',
    'LARÍSSA LACERDA LODONÍO',
    'LARISSA MACHADO ALMEIDA',
    'MARIA GABRIELA FERREIRA CUNHA',
    'MARIA LETICIA MEDEIROS MARINHO',
    'MARIA MADALENA FEITOSA',
    'MARINA GOMES DE CARVALHO',
    'MATHEUS RODRIGUES LINHARES',
    'MONALIZA CORREIA CLAUDINO',
    'MONIC ALVES DE LIMA',
    'NICOLE JOANE PEREIRA E SILVA',
    'OLGA MARIA ARRAIS FIRMINO',
    'PEDRO HENRIQUE XAVIER LOPES',
    'RENATO MORAES DA SILVA',
    'RYLIA PEREIRA RODRIGUES',
    'SALOMAO CRÔCE HERMINIO LEITAO',
    'SARA ARAUJO DE QUENTAL',
    'SUSANA SAMPAIO ARARUNA',
    'TAMMI RAISLA ROCHA GASPAR',
    'TEREZA MARIANA DE OLIVEIRA FREIRE',
    'THIAGO WALLISSON DE OLIVEIRA BARROS',
    'VICTOR LUIZ CALDAS CAMPOS',
]

juazeiro_fera_enem = [
    'ALISSA LAURA AMARO PEREIRA',
    'ANTÔNIO MATHEUS CRUZ PONTES APOLINÁRIO',
    'ARTHUR BRUNO DE ARAUJO VIDAL',
    'ARTHUR RYAN ALMEIDA MENDES',
    'ARTHUR VICTOR DA GRAÇA MACEDO',
    'BEATRIZ LIMA DE ANGELO',
    'CARLOS EMANUEL NOVAIS FERNANDES',
    'DAVI LEITE ALENCAR BEZERRA',
    'FERNANDO LUCAS DE SOUSA TIMOTEO',
    'FRANCISCA HELLEN CHAVES DOS SANTOS',
    'GIOVANNI ALDRIN E SILVA',
    'HEITOR BARROS BANTIM DE VASCONCELOS',
    'HELIO DANIEL ARAUJO LIMA',
    'HEMMILY VITÓRIA DOS SANTOS PARENTE',
    'JOÃO PEDRO DE OLIVEIRA LUSTOSA',
    'KAMILLY CRISTINA DOS SANTOS SILVA',
    'LOURENNY PEDROZA ALVES FIGUEIREDO',
    'MARCELA DA CRUZ ANTUNES',
    'MARCOS VINICIUS ALENCAR DIAS DE OLIVEIRA',
    'MARIA EDUARDA DE MELO CALDAS',
    'MARIA FERNANDA LEITE TAVARES',
    'MARIA LUIZA FEITOSA JUSTO XENOFONTE',
    'MATEUS GONÇALVES DE SOUZA',
    'PEDRO HENRIQUE BARROS DE SÁ',
    'PEDRO LUCAS ALENCAR ALVES',
    'VITÓRIA EMANUELY DA SILA SANTOS',
    'VYCTÓRIA ALCANTARA DE SOUZA',
    'WESLEY CARNEIRO VIEIRA',
    'YGOR JACOB TAVARES BEZERRA',
]

ppa_med = [
    'Amanda Celina Bueno Lage',        
    'Amanda Ribeiro Melo - PPA MED',        
    'Ana Cecília Faccioli Blum',        
    'Ana Clara Wimmer',        
    'Ana Gabrielaa Ribeiro Saad',        
    'Ana Julia Albuquerque',        
    'Ana Luiza Spinola',        
    'Ana Paula Ramos pimenta',        
    'Andre Albuquerque',        
    'ANDRE CAVALCANTI STROHER PPA MED',        
    'André Luiz Goncalves Dias',        
    'Andre Torres',        
    'Aron Gabriel Olinto Artiaga',        
    'AUGUSTO DE ASSUNÇÃO ANDRADE PPA MED',        
    'BARBARA DI PAULA PPA MED',        
    'Barbara Sthefany Queiroz',        
    'Beatriz Álvares Ferreira Midlej',        
    'Beatriz Freitas de Moura',        
    'Bernardo Ferreira Lopes PPA MED',        
    'Bianca Barbosa Salomão',        
    'Breno Lucas Soares Medrado',        
    'Bruna Neres Moreira da Fonseca',        
    'Carla Masson Matos',        
    'Carlos Henrique Silva de Jesus',        
    'DANIEL ABDIBOL',        
    'Davi Carvalho Barbosa',        
    'Douglas Araujo Menezes Filho',        
    'Eduardo Côrtes',        
    'Eduardo Valença Restivo',        
    'Estela Karen Lima Silva',        
    'Felipe Andrade',        
    'Felipe Dutra',        
    'Felipe Pereira',        
    'Fernanda Ribeiro Monteiro de Barros',        
    'Fernando Vieira bezerra',        
    'Gabriela Eckert Bullé',        
    'Giovana Jucá',        
    'Giulia Moraes Piazzi',        
    'GUILHERME LIMA LOPES FRANÇA PPA MED',        
    'Guilherme Ribeiro Mota',        
    'Gustavo Silva Simões',        
    'Helena de Sousa Valadares de Camargo',        
    'Jeferson de Sousa',        
    'jÉSSICA  DE LÚCIA PPA MED',        
    'Joao Pedro de Oliveira Sampaio',        
    'JULIA DE OLIVEIRA',        
    'Juliana Angelo Ferreira Santos',        
    'Julianne Basílio Dantas',        
    'Jullia Eduarda Feijó Belluco',        
    'Julliana Costa Neves',        
    'Lara Hiorrana de Souza Nascimento',        
    'Leonardo Dias Grespan',        
    'Letícia Cabral Torres',        
    'Linda Arueira e Quaresma',        
    'Lizienne Calazans de Oliveira',        
    'Lorena Costa Holanda',        
    'Lua Clara',        
    'Luanna Catharyna Santos de Souza Silva',        
    'Lucas Duarte do Amaral',        
    'Luisa Bandeira Castilho',        
    'Luisa Nunes Ferreira Ávila',        
    'Luiza de Freitas Araújo',        
    'Luiza Maria Dias Meirrelles PPA MED',        
    'Luiza Riguetto Augusto',        
    'Maria Eduarda Jordão',        
    'Maria Eduarda Mendes',        
    'Maria Helena',        
    'Maria Luisa Mirelle Duarte PPA MED',        
    'MARIA LUIZA DE ORNELAS NOBREGA',        
    'Mariana Assis Heider',        
    'Mariana mello',        
    'Maryna Maciel',        
    'Milenna de Souza Miranda Amâncio',        
    'Milenna Miranda',        
    'Paula Carvalho Damasceno',        
    'Pedro Henrique Andriani',        
    'Pedro Otávio Ottoni Ferreira',        
    'Pedro Parcianello',        
    'PPA MED ALUNO TESTE',        
    'Rafael Moraes de Faria',        
    'Renata Reis de Moura',        
    'Sarah Obeid Steckelberg',        
    'Secretaria PPA',        
    'Sofia Moreira da Costa Bernardi Pereira',        
    'Sofia Sousa Alexandre',        
    'Thainara Moura Cunha',        
    'Thássia Maria de Paula Gallo',        
    'Victor Felipe Becker Amaral Nunes',        
    'Vinicios Ramsés',        
    'yan trindade',
]

juazeiro = School.objects.get(name='Juazeiro')
for student_name in juazeiro_ppa_students:
    if len(Student.objects.all().filter(name=student_name)): continue
    Student(
        school=juazeiro,
        name=student_name,
        email='',
        identification='',
        year='',
        class_id='PPA'
    ).save()

for student_name in juazeiro_fera_enem:
    if len(Student.objects.all().filter(name=student_name)): continue
    Student(
        school=juazeiro,
        name=student_name,
        email='',
        identification='',
        year='',
        class_id='Fera ENEM'
    ).save()