# Generated by Django 3.0.3 on 2020-02-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destrator', '0003_auto_20200224_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='data',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tps',
            name='id',
            field=models.TextField(editable=False, primary_key=True, serialize=False),
        ),
    ]
