# Generated by Django 3.0.3 on 2020-03-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='nome')),
                ('url', models.TextField()),
                ('local', models.TextField(verbose_name='campus')),
                ('discipline', models.TextField(verbose_name='disciplina')),
                ('week', models.TextField(verbose_name='semana')),
                ('last_modified', models.DateField(verbose_name='última modificação')),
                ('answers', models.IntegerField(verbose_name='respostas')),
                ('data', models.BinaryField()),
                ('correct_answer_1', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 1')),
                ('correct_answer_2', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 2')),
                ('correct_answer_3', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 3')),
                ('correct_answer_4', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 4')),
                ('correct_answer_5', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 5')),
                ('correct_answer_6', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 6')),
                ('correct_answer_7', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 7')),
                ('correct_answer_8', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 8')),
                ('correct_answer_9', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 9')),
                ('correct_answer_10', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 10')),
            ],
            options={
                'verbose_name': 'relatório',
                'verbose_name_plural': 'relatórios',
                'ordering': ('name',),
            },
        ),
    ]
