# Generated by Django 3.0.3 on 2020-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
