# Generated by Django 3.0.3 on 2020-02-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0002_tps_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tps',
            options={'verbose_name': 'TPS', 'verbose_name_plural': 'TPS'},
        ),
        migrations.AlterField(
            model_name='tps',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tps',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tps',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tpsanswer',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tpsanswer',
            name='name',
            field=models.TextField(),
        ),
    ]
