# Generated by Django 3.0.3 on 2020-03-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0004_auto_20200228_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='local',
            field=models.TextField(default='JUAZEIRO'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tps',
            name='week',
            field=models.TextField(default='SEM1'),
            preserve_default=False,
        ),
    ]
