# Generated by Django 3.0.3 on 2020-03-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0005_auto_20200302_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tps',
            name='discipline',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
