# Generated by Django 3.0.3 on 2020-03-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0007_auto_20200303_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TPS',
            new_name='Report',
        ),
        migrations.DeleteModel(
            name='TPSAnswer',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('name',), 'verbose_name': 'Relatório', 'verbose_name_plural': 'Relatórios'},
        ),
    ]
