# Generated by Django 3.0.3 on 2020-03-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0008_auto_20200303_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='answers',
            field=models.IntegerField(verbose_name='Respostas'),
        ),
        migrations.AlterField(
            model_name='report',
            name='discipline',
            field=models.TextField(verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_modified',
            field=models.DateField(verbose_name='Última modificação'),
        ),
        migrations.AlterField(
            model_name='report',
            name='local',
            field=models.TextField(verbose_name='Campus'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.TextField(verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='report',
            name='week',
            field=models.TextField(verbose_name='Semana'),
        ),
    ]
