# Generated by Django 3.0.3 on 2020-03-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0009_auto_20200303_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('name',), 'verbose_name': 'relatório', 'verbose_name_plural': 'relatórios'},
        ),
        migrations.AlterField(
            model_name='report',
            name='answers',
            field=models.IntegerField(verbose_name='respostas'),
        ),
        migrations.AlterField(
            model_name='report',
            name='discipline',
            field=models.TextField(verbose_name='disciplina'),
        ),
        migrations.AlterField(
            model_name='report',
            name='last_modified',
            field=models.DateField(verbose_name='última modificação'),
        ),
        migrations.AlterField(
            model_name='report',
            name='local',
            field=models.TextField(verbose_name='campus'),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.TextField(verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='report',
            name='week',
            field=models.TextField(verbose_name='semana'),
        ),
    ]
