# Generated by Django 3.0.3 on 2020-03-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0011_auto_20200304_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='correct_answer_1',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct_answer_10',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 10'),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct_answer_2',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct_answer_3',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct_answer_4',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 4'),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct_answer_5',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 5'),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct_answer_6',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 6'),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct_answer_7',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 7'),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct_answer_8',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 8'),
        ),
        migrations.AlterField(
            model_name='report',
            name='correct_answer_9',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='', max_length=1, verbose_name='gabarito questão 9'),
        ),
    ]
